config/routes.rb
Rails.application.routes.draw do
  root to: 'things#index'
  resources :things do
    post :update_row_order, on: :collection
  end
end

app/models/thing.rb
class Thing < ActiveRecord::Base
  include RankedModel
  ranks :row_order
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :set_thing, only: [:show, :edit, :update, :destroy]

  # GET /things
  # GET /things.json
  def index
    @things = Thing.rank(:row_order).all
  end

  # GET /things/1
  # GET /things/1.json
  def show
  end

  def update_row_order
    @thing = Thing.find(thing_params[:thing_id])
    @thing.row_order_position = thing_params[:row_order_position]
    @thing.save

    render nothing: true # this is a POST action, updates sent via AJAX, no view rendered
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing
      @thing = Thing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thing_params
      params.require(:thing).permit(:thing_id, :title, :description, :row_order_position)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Sortable Bootstrap Tables in Rails — http://benw.me</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= yield %>
        </div>
      </div>
    </div>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>

app/views/things/index.html.erb
<h1>Sortable Bootstrap Tables in Rails (drag &amp; drop reordering)</h1>
<h5>
  <%= link_to 'http://benw.me/posts/sortable-bootstrap-tables/', 'http://benw.me/posts/sortable-bootstrap-tables/' %>
</h5>
<div class="panel panel-default">
  <table class="table table-bordered table-striped" id="sortable">
    <thead>
      <tr>
        <th>
          Title
        </th>
        <th>
          Description
        </th>
      </tr>
    </thead>
    <tbody>
      <% @things.each do |thing| %>
        <tr data-item-id=<%= "#{thing.id}" %> class="item">
          <td>
            <%= thing.title %>
          </td>
          <td>
            <%= link_to 'show', thing_path(thing), :class => 'btn btn-default pull-right' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/things/show.html.erb
<h1></h1>
<div class="panel panel-default">
  <div class="panel-heading">
    <%= @thing.title %>
  </div>
  <div class="panel-body">
    <%= @thing.description %>
  </div>
</div>
<%= link_to 'Back', things_path %>